<?php require_once 'config/config.php'; require_room(); $rid=room_id();$st=db()->prepare("SELECT * FROM rooms WHERE id=?");$st->execute([$rid]);$room=$st->fetch();
$members=db()->prepare("SELECT rm.*,u.name,u.email FROM room_members rm JOIN users u ON u.id=rm.user_id WHERE rm.room_id=? AND rm.status='active' ORDER BY rm.role='manager' DESC,u.name");$members->execute([$rid]);$members=$members->fetchAll();
$today=date('Y-m-d');$month=date('Y-m');$x=db()->prepare("SELECT COALESCE(SUM(amount),0) FROM expenses WHERE room_id=? AND expense_date BETWEEN ? AND ?");$x->execute([$rid,date('Y-m-01'),$today]);$expense=(float)$x->fetchColumn();
$days=(int)date('j');$sessions=(int)$room['meal_times'];$membersCount=count($members);$moff=db()->prepare("SELECT COUNT(*) FROM meals WHERE room_id=? AND meal_date BETWEEN ? AND ? AND status='off'");$moff->execute([$rid,date('Y-m-01'),$today]);$off=(int)$moff->fetchColumn();$meals=max(0,$membersCount*$days*$sessions-$off);
$rate=$meals?($expense/$meals):0;
$title='Dashboard';include 'includes/header.php';?>
<div class="d-flex flex-wrap justify-content-between align-items-center mb-4"><div><div class="small-muted">Room</div><h2 class="fw-bold mb-0"><?=e($room['name'])?></h2><span class="badge badge-soft mt-2"><?=e(room_role())?></span></div><div class="d-flex gap-2"><a href="meals.php" class="btn btn-dark"><i class="bi bi-calendar2-check"></i> Meals</a><?php if(room_role()==='manager'):?><a href="room.php" class="btn btn-outline-dark">Manage room</a><?php endif;?></div></div>
<div class="row g-3 mb-4"><div class="col-md-3"><div class="card metric p-3"><div class="icon"><i class="bi bi-people"></i></div><div class="small-muted mt-3">Members</div><div class="stat-number"><?=count($members)?></div></div></div><div class="col-md-3"><div class="card metric p-3"><div class="icon"><i class="bi bi-cart3"></i></div><div class="small-muted mt-3">Month expense</div><div class="stat-number"><?=money($expense)?></div></div></div><div class="col-md-3"><div class="card metric p-3"><div class="icon"><i class="bi bi-egg-fried"></i></div><div class="small-muted mt-3">Month meals</div><div class="stat-number"><?=$meals?></div></div></div><div class="col-md-3"><div class="card metric p-3"><div class="icon"><i class="bi bi-graph-up"></i></div><div class="small-muted mt-3">Meal rate</div><div class="stat-number"><?=money($rate)?></div></div></div></div>
<div class="row g-4"><div class="col-lg-8"><div class="card p-4"><div class="d-flex justify-content-between"><h5 class="fw-bold">Monthly snapshot</h5><span class="small-muted"><?=e($month)?></span></div><canvas id="expenseChart" height="110"></canvas></div></div><div class="col-lg-4"><div class="card p-4 room-access-card"><div class="d-flex justify-content-between align-items-center"><h5 class="fw-bold mb-0">Room access</h5><span class="badge badge-soft">Invite</span></div><p class="small-muted mt-3 mb-1">Room code</p><div class="room-code-display"><?=e($room['room_code'])?></div><div class="qr-box mt-3" id="qrcode"></div><div class="d-grid gap-2 mt-3"><button type="button" class="btn btn-dark" id="copyRoomCodeDash"><i class="bi bi-copy"></i> Copy room code</button><button type="button" class="btn btn-light" id="copyJoinLinkDash"><i class="bi bi-link-45deg"></i> Copy join link</button></div><div class="small-muted mt-3">Members can scan the QR or use the code to join this room.</div></div></div></div>
<div class="card p-4 mt-4"><div class="d-flex justify-content-between align-items-center"><h5 class="fw-bold mb-0">Members</h5><a href="payments.php" class="btn btn-sm btn-light">View balances</a></div><div class="table-responsive mt-3"><table class="table align-middle"><thead><tr><th>Name</th><th>Role</th><th>Meals this month</th><th>Paid</th></tr></thead><tbody><?php foreach($members as $mm):$q=db()->prepare("SELECT COUNT(*) FROM meals WHERE room_id=? AND user_id=? AND meal_date BETWEEN ? AND ? AND status='off'");$q->execute([$rid,$mm['user_id'],date('Y-m-01'),$today]);$offm=(int)$q->fetchColumn();$mc=max(0,$days*$sessions-$offm);$q=db()->prepare("SELECT COALESCE(SUM(amount),0) FROM payments WHERE room_id=? AND user_id=? AND payment_date BETWEEN ? AND ?");$q->execute([$rid,$mm['user_id'],date('Y-m-01'),$today]);$paid=(float)$q->fetchColumn();?><tr><td><?=e($mm['name'])?></td><td><span class="badge text-bg-light"><?=e($mm['role'])?></span></td><td><?=$mc?></td><td><?=money($paid)?></td></tr><?php endforeach;?></tbody></table></div></div>
<script>const dashJoinUrl=location.origin+location.pathname.replace('dashboard.php','join-room.php')+'?code=<?=e($room['room_code'])?>';new QRCode(document.getElementById('qrcode'),{text:dashJoinUrl,width:180,height:180});document.getElementById('copyRoomCodeDash').addEventListener('click',async()=>{await navigator.clipboard.writeText('<?=e($room['room_code'])?>');document.getElementById('copyRoomCodeDash').innerHTML='<i class="bi bi-check2"></i> Copied';});document.getElementById('copyJoinLinkDash').addEventListener('click',async()=>{await navigator.clipboard.writeText(dashJoinUrl);document.getElementById('copyJoinLinkDash').innerHTML='<i class="bi bi-check2"></i> Link copied';});new Chart(document.getElementById('expenseChart'),{type:'line',data:{labels:['Week 1','Week 2','Week 3','Week 4'],datasets:[{label:'Expenses',data:[<?=round($expense*.18,2)?>,<?=round($expense*.32,2)?>,<?=round($expense*.21,2)?>,<?=round($expense*.29,2)?>],tension:.35}]},options:{plugins:{legend:{display:false}},responsive:true}});</script>
<?php include 'includes/footer.php';?>